version: 2.1

orbs:
  node: circleci/node@4.1.0
  codecov: codecov/codecov@1.1.1

node_executor: &node_executor
  name: node/default
  tag: '12.16'

jobs:
  lint:
    description: Run lint
    executor: *node_executor
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Run lint
          command: npm run lint
  tests:
    description: Run tests
    executor: *node_executor
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Run tests
          command: npm test
      - run:
          name: Upload coverage
          command: npx codecov

workflows:
  version: 2.1
  mongoose-fuzzy-searching:
    jobs:
      - lint
      - tests:
          requires:
            - lint
      - consent:
          type: approval
