version: 2.1

orbs:
  node: circleci/node@4.1.0
  codecov: codecov/codecov@1.1.1

commands:
  git_config_user:
    description: Configure git user
    parameters:
      user:
        type: string
        default: '${GIT_USERNAME}'
      email:
        type: string
        default: '${GIT_EMAIL}'
    steps:
      - run:
          name: Configure git user
          command: |
            git config --global user.email "<< parameters.email >>"
            git config --global user.name "<< parameters.user >>"
  publish_to_npm:
    description: Publish to npm
    parameters:
      token:
        type: string
        default: '${NPM_TOKEN}'
    steps:
      - run:
          name: Publish to npm
          command: |
            echo //registry.npmjs.org/:_authToken="<< parameters.token >>" > ~/.npmrc
            npm publish

verion_filter: &verion_filter
  filters:
    tags:
      only: /^v.*/
    branches:
      ignore: /.*/

node_executor: &node_executor
  name: node/default
  tag: '12.16'

jobs:
  lint:
    description: Run lint
    executor: *node_executor
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Run lint
          command: npm run lint
  tests:
    description: Run tests
    executor: *node_executor
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Run tests
          command: npm test
      - run:
          name: Upload coverage
          command: npx codecov
  publish:
    description: Publish to npm
    executor: *node_executor
    steps:
      - checkout
      - git_config_user
      - publish_to_npm

workflows:
  version: 2.1
  mongoose-fuzzy-searching:
    jobs:
      - lint
      - tests:
          requires:
            - lint
  mongoose-fuzzy-searching-publish:
    jobs:
      - publish:
          <<: *verion_filter
          name: Publish to npm
